name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build and push to ECR.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

     #   - name: Set up Docker Buildx
     #   uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t my-app .
          docker tag my-app:latest <aws_account_id>.dkr.ecr.<region>.amazonaws.com/my-app-repo:latest
          docker push <aws_account_id>.dkr.ecr.<region>.amazonaws.com/my-app-repo:latest

      - name: Trivy Scan
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL <aws_account_id>.dkr.ecr.<region>.amazonaws.com/my-app-repo:latest

      - name: Clean up old images
        run: |
          aws ecr list-images --repository-name my-app-repo --query 'imageIds[?imageTag!=`latest`]' --output json | jq -r '.[] | select(.imageTag | test("^[0-9]+$")) | .imageTag' | sort -r | tail -n +4 | xargs -I {} aws ecr batch-delete-image --repository-name my-app-repo --image-ids imageTag={}
